/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(home)': RouteRecordInfo<
      '/(home)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/animations': RouteRecordInfo<
      '/animations',
      '/animations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/charts': RouteRecordInfo<
      '/charts',
      '/charts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components': RouteRecordInfo<
      '/components',
      '/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content': RouteRecordInfo<
      '/content',
      '/content',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/eui-components': RouteRecordInfo<
      '/eui-components',
      '/eui-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forms': RouteRecordInfo<
      '/forms',
      '/forms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/markdown': RouteRecordInfo<
      '/markdown',
      '/markdown',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/supabase': RouteRecordInfo<
      '/supabase',
      '/supabase',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/typography': RouteRecordInfo<
      '/typography',
      '/typography',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home).vue': {
      routes:
        | '/(home)'
      views:
        | never
    }
    'src/pages/animations.vue': {
      routes:
        | '/animations'
      views:
        | never
    }
    'src/pages/charts.vue': {
      routes:
        | '/charts'
      views:
        | never
    }
    'src/pages/components.vue': {
      routes:
        | '/components'
      views:
        | never
    }
    'src/pages/content.vue': {
      routes:
        | '/content'
      views:
        | never
    }
    'src/pages/eui-components.vue': {
      routes:
        | '/eui-components'
      views:
        | never
    }
    'src/pages/forms.vue': {
      routes:
        | '/forms'
      views:
        | never
    }
    'src/pages/markdown.md': {
      routes:
        | '/markdown'
      views:
        | never
    }
    'src/pages/supabase.vue': {
      routes:
        | '/supabase'
      views:
        | never
    }
    'src/pages/typography.vue': {
      routes:
        | '/typography'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
